#!/bin/sh

DBSPACE=/opt/dbspace
DBSPACE_RW=/opt/usr/dbspace
APPS_DIR=/opt/apps
SHARE_DIR=/opt/share

chown 5000:5000 /home/app



# set vconf label when first boot
#if [ ! -e /opt/etc/.vconf_labeling ]; then
#	touch /opt/etc/.vconf_labeling
#fi

# Set device node permissions for security

echo "0.0.0.0/1 system::use_internet" >> /smack/netlabel
echo "128.0.0.0/1 system::use_internet" >> /smack/netlabel
echo "127.0.0.1 -CIPSO" >> /smack/netlabel
echo "192.168.129.1 @" >> /smack/netlabel
echo "system::use_internet" > /smack/ambient

# Set label to database files

